version: '3.9'
services:
  db:
    image: mysql:8.0.32
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_ifind
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - ifind-network
  rest-with-spring-boot-ifind:
    image: germanofortuna/rest-with-spring-boot-ifind
    restart: always
    build: ./i-find
    working_dir: /i-find
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_ifind?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command:
      - mvn spring-boot:run
    depends_on:
      - db
    networks:
      - ifind-network
networks:
  ifind-network:
    driver:  bridge